name: Daily Sync to Org Repo

on:
  push:
    branches:
      - main
      
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to Organization Repo
        env:
          ORG_PUSH_TOKEN: ${{ secrets.ORG_PUSH_TOKEN }}
        run: |
          git remote add org-repo https://NEYXHQ:${ORG_PUSH_TOKEN}@github.com/NEYXHQ/vending-machine-app.git
          git push org-repo main
